FROM ubuntu:20.04

# https://github.com/moby/moby/issues/4032#issuecomment-163689851
# https://github.com/moby/moby/issues/4032#issuecomment-192327844

#ENV  http_proxy="http://10.158.100.2:8080/"
#ENV  https_proxy="http://10.158.100.2:8080/"
#ENV  ftp_proxy="http://10.158.100.2:8080/"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing && apt-get upgrade -y
RUN apt-get install -y \
    wget \
    tar \
    openjdk-11-jdk

ENV SPARK_VERSION=3.1.3
ENV HADOOP_VERSION=3.2
ENV SPARK_HOME=/root/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}

ENV SPARK_MASTER_PORT=7077
ENV SPARK_UI_PORT=8080

# Download spark binaries
RUN cd /tmp && \
    #wget https://dlcdn.apache.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop3.2.tgz
    wget https://dlcdn.apache.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop3.2.tgz

# Install spark binaries to home directory (matching flintrock)
RUN cd ~ && \
    tar -vxf /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    rm /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
