name: dizk-ci

on:
    push:
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: '11'
            - name: Run tests with Maven
              run: SPARK_LOCAL_IP=127.0.0.1 mvn clean test

    check-fmt:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: '11'
            - name: Check code fmt
              run: mvn -q spotless:check

    docker-build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Build docker containers
              run: |
                  scripts/local-cluster-setup.sh
                  scripts/dev-setup.sh
            - name: Start local cluster
              run: |
                  docker-compose -f scripts/local_cluster/docker-compose.yml up -d
            - name: Build prover in dev container
              run: |
                  docker start dizk
                  docker exec dizk mvn package -Dmaven.test.skip=true
            - name: Run trivial test on local cluster
              run: |
                  docker exec dizk ./run-prover --test
            - name: Run trivial test on local cluster
              run: |
                  docker exec dizk ./run-prover test_data/simple_proving_key_GROTH16_alt-bn128.bin test_data/simple_assignment_alt-bn128.bin
            - name: Stop dev container and local cluster
              run: |
                  docker stop dizk
                  docker-compose -f scripts/local_cluster/docker-compose.yml down
